### ISSUE TITLE
Pipes Not Next To Inventories Ignored

### ISSUE THREAD

**Issue by JoshMayberry** [cakewhip/ezpas#12]
The main page says "prior to version 1.1.0, filtered pipes had to be placed right next to inventories".
If I have a non-filter pipe between a filter and a chest, the filter is ignored.

I assume the advanced filtering option "Persist to Other Pipes" is what determines if the old behavior (filters not next to inventories are ignored) applies or not. I tried it with this option both on and off, and saw no difference.

**Comment by JoshMayberry** [comment]
As an example of why this is an issue, say you want to have pipes filtering items for a piglin baretring farm, and you want the chests next to each other like this:
![image](https://user-images.githubusercontent.com/11482252/90348231-116b7480-e003-11ea-9557-dc426f859b12.png)



If filters cannot be next to each other, then they need to be spaced out like this, which can get very large.
Top view:
![image](https://user-images.githubusercontent.com/11482252/90348200-d8330480-e002-11ea-8fc6-fd41ddf74ce6.png)

Side view:
![image](https://user-images.githubusercontent.com/11482252/90348257-37911480-e003-11ea-9042-5caa05db8701.png)

Angle View:
![image](https://user-images.githubusercontent.com/11482252/90348275-51caf280-e003-11ea-9cf8-07e077f564e2.png)

**Comment by cakewhip** [comment]
Yes, persist to other pipes is the correct flag for the situation you described. It should be fixed as of v1.2.1. If it isn't (🤞) just reopen this again.
