### ISSUE TITLE
Neighboring Pipe Filters Combining

### ISSUE THREAD

**Issue by JoshMayberry** [cakewhip/ezpas#13]
If I have two filters next to each other like this:
![image](https://user-images.githubusercontent.com/11482252/90320764-d0476780-df11-11ea-9a98-44edce137669.png)

Then filter A bleeds over into filter B.
The pipe probe says that the barrel connected to filter A has only filter A applied.
The barrel connected to filter B has both filter A and filter B applied.

This is the same if the "Persist to other pipes" flag is set to true or false.

_Is there a way I can disconnect the two filter pipes from each other, but still have them next to each other?_
Perhaps if I were to shift-right-click on a connection while holding the pipe probe, it would disconnect the two pipes from each other?
Or perhaps, an advanced filtering option could be for the filter to only connect along the x-axis, y-axis, or z-axis (in a straight line)?
Or perhaps, like the colored pipes, I could apply a color to the filter?
Or perhaps, like in Thermal Expansion machines, the GUI could have an enable/disable connectable-direction thing?
Or perhaps, an item like a Build craft Facade can be placed on one side of the filter to prevent them from connecting?

**Comment by cakewhip** [comment]
The filter bleeding has been fixed, just need to make a release. As for solutions to disconnect the filter pipes, currently weighting the various solutions in terms of how they'd fit in with the mod in its current state. Pipe connections will most likely be the next big thing I work on.

**Comment by JoshMayberry** [comment]
As long as the bleeding is fixed, disconnecting them is not as critical. :)

**Comment by JoshMayberry** [comment]
How is the release with the filter bleeding fix coming? :)

**Comment by cakewhip** [comment]
The persistence issues should be fixed now as of v1.2.1. Had to take a small break, but updates should be flowing again now. 👍

**Comment by JoshMayberry** [comment]
Awesome. I guess that version isn't on curseforge yet.
:) Breaks are fine, just following up- no pressure.
