### ISSUE TITLE
Enhancement: dense pipes

### ISSUE THREAD

**Issue by ghost** [cakewhip/ezpas#2]
Sometimes round-robin distribution isn't the wanted behavior.  Instead of working with fixed priorities, a dense pipe could be added to the pipe network.
Items would only cross a dense pipe, after they can't be inserted into any inventory in front of the dense pipe.

A use-case:
Iron ingots are retrieved from a furnace and stored by ezpas in a chest.  Further down the line is an auto crafter making iron blocks.
With the current network, both the chest and auto crafter would be supplied with iron ingots, with no priority.
With the dense pipe between the chest and the auto crafter, first the chest would be filled with ingots. Only after no more ingots can be deposited in the chest, they are delivered to the auto crafter.

**Comment by cakewhip** [comment]
I'm a fan of this. Started development today 👍

**Comment by cakewhip** [comment]
Dense pipes have been added as of v1.1.0
