### ISSUE TITLE
Dank Dock + Ezpas pipes not filling dank properly

### ISSUE THREAD

**Issue by Yoosk** [cakewhip/ezpas#22]
https://github.com/Tfarcenim/DankStorageFabric/issues/7

**Comment by cakewhip** [comment]
As of v2.0.0, EZPaS now suports Fabric API's item transportation API. If this issue still exists, it is because the other mod needs to support this integration.

**Comment by luiz00martins** [comment]
@cakewhip Hi! Thank you for the great mod!

Do you have any plans to (or is it even possible to) implement the API in the 1.16.5 version?

I've been using EZPaS with dank dock and encountered the same problem (everything capping at 64).

Edit: After testing with other mods such as [pipe](https://www.curseforge.com/minecraft/mc-mods/pipe), and the same problem occurred, so it seems like it's a more widespread thing. However, it suffices to use a hopper as a middleman (for both mods).
