### ISSUE TITLE
Any plans to update to 1.17.1?

### ISSUE THREAD

**Issue by NOOTLORD** [cakewhip/ezpas#28]
Ive noticed there are a lack of good pipe mods for fabric (for now) and this 1 does fill my needs but i was wondering if there are plans to port it to 1.17.1.

**Comment by cakewhip** [comment]
Will update EZPaS soon 👍 (hopefully within a week-ish)

**Comment by NOOTLORD** [comment]
Hi there,
Cheers for the headsup i will await its release.
