### ISSUE TITLE
Enhancement: Match Ore Dictionary, Ignore Durability, etc.

### ISSUE THREAD

**Issue by JoshMayberry** [cakewhip/ezpas#3]
Very cool mod! I am glad to be working with pipes again in minecraft.

It would be very cool if more filtering options were available, like in EnderIO.

Upgrades could be applied to the filter pipe which makes it's behavior change (like how some black dye makes it a blacklist instead of a white list). Maybe the could be applied by crafting the filter with other items.

Here are some examples of different filter modifiers, as well as an example item that they could be crafted with:

- Coal: _Match Ore dictionary_
- String: _Ignore Metadata_
- Emerald: _Ignore Name From Anvil_
- Redstone: _Will disable the filter when a redstone signal is received_
- Gunpowder: _Will reject everything when a redstone signal is received_
- Bone Meal: _Ignore NBT_
- Glowstone: _Match any items from the same mod_
- Iron Nugget: _Ignore Damage_
- Empty Bottle: _At least 1 of this item must be in the inventory_
- Water Bottle: _At least 1 of this item must NOT be in the inventory_
- Ender Pearl: _Will only fill up the chest with as many stacks of the item that there are items of it's kind in the filter's inventory_

So, if you were to craft a filter with some coal and then with some bone meal, it would both ignore damage and ignore NBT.

If you were to craft a filter with an ender pearl and put 4 oak planks in the first filter slot and 3 cobble stone in the second filter slot- then it would only place up to 4 stacks of oak planks and 3 stacks of cobble stone in it.

**Comment by cakewhip** [comment]
Lots of good ideas here. I have a bunch of features already in the upcoming release, so these will most likely be included in the following release. Thanks!

**Comment by cakewhip** [comment]
Some of these features have been added as of v1.2.0, others are under consideration still

**Comment by JoshMayberry** [comment]
Very cool. I love the advanced filtering menu! Well done.
