### ISSUE TITLE
Enhancement: Pipes That Don't Connect to Inventories

### ISSUE THREAD

**Issue by JoshMayberry** [cakewhip/ezpas#4]
It would be very cool if a pipe was available that does not connect to inventories, but connects to other pipes, like the BuildCraft sandstone pipe, or a wrench that could remove connections to an inventory.

For example, I could craft any pipe together with some sand, which would give me a version of that pipe that would not connect to inventories.

**Comment by cakewhip** [comment]
Noted, thanks for the suggestion!

**Comment by cakewhip** [comment]
Rigid pipes have been added as of v1.1.0
