### ISSUE TITLE
Direct use of Dense pipes will cause the game to crash.

### ISSUE THREAD

**Issue by BlueSkyClouds** [cakewhip/ezpas#6]
![2020-08-09_15 31 49](https://user-images.githubusercontent.com/39831773/89727274-9bd93480-da55-11ea-9c00-58d946404552.png)

The judgment can be increased appropriately to prevent the game from crashing due to the player's wrong placement

**Comment by cakewhip** [comment]
This has been fixed as of v1.1.1, thank you!
